/*
*------------------------------------------------------------------------------
* <auto-generated>
*     This code was generated by a tool.
*     Runtime Version:0.7.5.0
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*------------------------------------------------------------------------------
*/

class library extends MfObject
{
    bookField := MfNull.Null
    
    
    __New(){
        base.__New()
        this.bookField :=  new MfGenericList(libraryBook)
        this.m_isInherited := this.base.__Class != "library"
        
    }
    
    book[]
    {
        get
        {
            return this.bookField
        }
        set
        {
            this.bookField := value
            return this.bookField
        }
    }
    
    
    _NewEnum() {
        return new library.Enumerator(this)
    }
    
    ; Internal Class
    class Enumerator
    {
        m_Parent := Null
        m_KeyEnum := Null
        m_index := 0
        m_count := 0
        
        __new(ParentClass) {
            this.m_Parent := ParentClass
            this.m_count := this.m_Parent.book.Count
        }
        
        Next(ByRef key, ByRef value)
        {
            if (this.m_index < this.m_count)
            {
                key := this.m_index
                value := this.m_Parent.book.Item[key]
            }
            this.m_index++
            if (this.m_index > this.m_count)
            {
                return 0
            }
            else
            {
                return true
            }
        }
    }
}

class libraryBook extends MfObject
{
    isbnField := ""
    titleField := MfNull.Null
    authorField := MfNull.Null
    characterField := MfNull.Null
    idField := ""
    availableField := false
    availableFieldSpecified := false
    
    
    __New(){
        base.__New()
        this.titleField := new libraryBookTitle()
        this.authorField :=  new MfGenericList(libraryBookAuthor)
        this.characterField :=  new MfGenericList(libraryBookCharacter)
        this.availableField := false
        this.availableFieldSpecified := false
        this.m_isInherited := this.base.__Class != "libraryBook"
        
    }
    
    isbn[]
    {
        get
        {
            return this.isbnField
        }
        set
        {
            this.isbnField := value
            return this.isbnField
        }
    }
    
    title[]
    {
        get
        {
            return this.titleField
        }
        set
        {
            this.titleField := value
            return this.titleField
        }
    }
    
    author[]
    {
        get
        {
            return this.authorField
        }
        set
        {
            this.authorField := value
            return this.authorField
        }
    }
    
    character[]
    {
        get
        {
            return this.characterField
        }
        set
        {
            this.characterField := value
            return this.characterField
        }
    }
    
    id[]
    {
        get
        {
            return this.idField
        }
        set
        {
            this.idField := value
            return this.idField
        }
    }
    
    available[]
    {
        get
        {
            return this.availableField
        }
        set
        {
            this.availableField := value
            return this.availableField
        }
    }
    
    availableSpecified[]
    {
        get
        {
            return this.availableFieldSpecified
        }
        set
        {
            this.availableFieldSpecified := value
            return this.availableFieldSpecified
        }
    }
    
}

class libraryBookTitle extends MfObject
{
    langField := ""
    valueField := ""
    
    
    __New(){
        base.__New()
        this.m_isInherited := this.base.__Class != "libraryBookTitle"
        
    }
    
    lang[]
    {
        get
        {
            return this.langField
        }
        set
        {
            this.langField := value
            return this.langField
        }
    }
    
    Value[]
    {
        get
        {
            return this.valueField
        }
        set
        {
            this.valueField := value
            return this.valueField
        }
    }
    
}

class libraryBookAuthor extends MfObject
{
    nameField := MfNull.Null
    bornField := ""
    deadField := ""
    idField := ""
    
    
    __New(){
        base.__New()
        this.nameField := new libraryBookAuthorName()
        this.m_isInherited := this.base.__Class != "libraryBookAuthor"
        
    }
    
    name[]
    {
        get
        {
            return this.nameField
        }
        set
        {
            this.nameField := value
            return this.nameField
        }
    }
    
    born[]
    {
        get
        {
            return this.bornField
        }
        set
        {
            this.bornField := value
            return this.bornField
        }
    }
    
    dead[]
    {
        get
        {
            return this.deadField
        }
        set
        {
            this.deadField := value
            return this.deadField
        }
    }
    
    id[]
    {
        get
        {
            return this.idField
        }
        set
        {
            this.idField := value
            return this.idField
        }
    }
    
}

class libraryBookAuthorName extends MfObject
{
    firstField := ""
    middleField := ""
    lastField := ""
    
    
    __New(){
        base.__New()
        this.m_isInherited := this.base.__Class != "libraryBookAuthorName"
        
    }
    
    first[]
    {
        get
        {
            return this.firstField
        }
        set
        {
            this.firstField := value
            return this.firstField
        }
    }
    
    middle[]
    {
        get
        {
            return this.middleField
        }
        set
        {
            this.middleField := value
            return this.middleField
        }
    }
    
    last[]
    {
        get
        {
            return this.lastField
        }
        set
        {
            this.lastField := value
            return this.lastField
        }
    }
    
}

class libraryBookCharacter extends MfObject
{
    nameField := ""
    bornField := ""
    qualificationField := ""
    idField := ""
    
    
    __New(){
        base.__New()
        this.m_isInherited := this.base.__Class != "libraryBookCharacter"
        
    }
    
    name[]
    {
        get
        {
            return this.nameField
        }
        set
        {
            this.nameField := value
            return this.nameField
        }
    }
    
    born[]
    {
        get
        {
            return this.bornField
        }
        set
        {
            this.bornField := value
            return this.bornField
        }
    }
    
    qualification[]
    {
        get
        {
            return this.qualificationField
        }
        set
        {
            this.qualificationField := value
            return this.qualificationField
        }
    }
    
    id[]
    {
        get
        {
            return this.idField
        }
        set
        {
            this.idField := value
            return this.idField
        }
    }
    
}

